# Generated by Django 6.0.3 on 2026-04-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
    ]
