# Generated by Django 6.0.3 on 2026-04-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-created_at']},
        ),
    ]
