# Generated by Django 6.0.3 on 2026-04-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_photo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='bio',
            new_name='description',
        ),
    ]
